general-settings:
  auto-save: true
  saving-interval-hours: 12
  guild-id: ""
  general-prefix: "="
validation:
  prefix: "LINK "# Case-Sensitive
  receive-in-channel-id: ""
  notify-in-channel-id: ""
