name: DiscordLink
version: ${project.version}
main: com.nations.discordlink.DiscordLink
api-version: 1.16
authors: [Nebula_1]
commands:
  discordlink:
    usage: /discordlink
    aliases:
      - dlink
    permission: discordlink.discordlink
  band:
    usage: /band [IGN] [Number of days of messages to delete]
    description: Ban a player's linked discord account (on Discord only).
    aliases:
      - bandiscord
      - banondiscord
      - discordban
      - discban
    permission: discordlink.bandiscord
permissions:
  discordlink.bandiscord:
    description: Ban a player's linked discord account on Discord.
    default: op
  discordlink.discordlink:
    description: Manage DiscordLink.
    default: op